#!/bin/sh
blue='\033[0;34m'
no_color='\033[0m'

. "$(dirname "$0")/_/husky.sh"

# Check Prettier
echo "\n${blue}Prettier Checking...${no_color}"
npm run format-prettier ||
{
  echo "\n${blue}Prettier - Trying to formatting...${no_color}"

  npm run format
  git add .
}

npm run lint
npx lint-staged
